### ISSUE TITLE
Initial AudioManager

### ISSUE THREAD

**Issue by Per-Morten** [Per-Morten/imt4310_conductor_hero#24]
- [x] Get/SetVolume
- [x] Multiple Tracks (at same time)
- [x] Muting of individual tracks (will be used for cue-ing)
- [x] Start - Stop tracks (PlayScheduled)

**Comment by aniWeyn** [comment]
//This script allows you to toggle music to play and stop.
https://docs.unity3d.com/ScriptReference/AudioSource.html

**Comment by aniWeyn** [comment]
Volume:
https://docs.unity3d.com/ScriptReference/AudioSource-volume.html
